name: Build, test and deploy
on: [push]
jobs:
  build-test-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose up --build --detach
